### PR TITLE
Translatable trait fix

### PR DESCRIPTION
**Pull request by TomasPilaru**
Add 'get' prefix only if name doesn't contain prefixes like: is, has, should.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Could you also provide also test for this use case?

**Comment by TomasPilaru** [comment]
Hi, test added.

**Comment by TomasVotruba** [comment]
Thank you!

**Comment by TomasVotruba** [comment]
Merged and released new version: https://github.com/Zenify/DoctrineBehaviors/releases/tag/v2.2.0

Test pls!

**Comment by TomasPilaru** [comment]
Thanks, works fine!

**Comment by TomasVotruba** [comment]
Great, thank you

**Pull request merged**
