### PR TITLE
composer: fix typo

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by enumag** [comment]
Nice catch!

**Comment by TomasVotruba** [comment]
Thank you!

**Comment by enumag** [comment]
Finally managed to fix the travis as well. There is one more problem on localhost though - this [line](https://github.com/Zenify/DoctrineBehaviors/blob/master/tests/bootstrap.php#L12) throws an exception:

```
Nette\IOException: Unable to delete '...\tests/temp\8508\cache\journal.s3db'. in ...\vendor\nette\utils\src\Utils\FileSystem.php on line 77
```

Do you have some idea how to fix it?

**Comment by TomasVotruba** [comment]
It looks like Windows/*nix directory separator issue.

I'd use `DIRECTORY_SEPARATOR` constant.

**Comment by enumag** [comment]
That's not it. The journal file is still in use for some reason.

**Comment by TomasVotruba** [comment]
Dunno then. What OS do you use? 
I can't help with Windows. Might try on Linux though.

**Comment by enumag** [comment]
Right... could you try running the tests locally to see if you get the same error?

**Comment by TomasVotruba** [comment]
All fine with me...

image

**Pull request merged**
