### PR TITLE
TreeExtension added

### PR DESCRIPTION
**Pull request by hranicka**
This adds missing [Tree](https://github.com/KnpLabs/DoctrineBehaviors#tree) support like Nette Extension.

### CODE REVIEW

**Comment by enumag** [comment]
I'd probably recommend https://github.com/Zenify/DoctrineExtensionsTree (it uses Gedmo) instead but we can have this as well I guess. I have to ask you to add some tests first though.

**Comment by enumag** [comment]
@hranicka GitHub doesn't send any notification when you push something so next time ping me to make sure I notice it. ;-)

Everything looks good. Just squash it into a single commit please.

**Comment by hranicka** [comment]
@enumag 
I've squashed commits.

**Comment by enumag** [comment]
@hranicka Merged. Thanks for your contribution! :-)

**Pull request merged**
